name: Sync README from AdvancedArmorStands

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # runs daily at midnight, adjust as needed

jobs:
  sync-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 1

      - name: Checkout AdvancedArmorStands repo
        uses: actions/checkout@v3
        with:
          repository: Parsa3323/AdvancedArmorStands
          path: profile
          ref: master
          fetch-depth: 1

      - name: Remove old README and copy new one
        run: |
          rm -f README.md
          cp profile/README.md README.md



      - name: Commit and push
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "Force sync README.md from AdvancedArmorStands" --allow-empty
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}
          git push origin main

      

