name: Sync README

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'README.md'

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync README
        uses: BetaHuhn/readme-sync-action@v2
        with:
          source-repository: Parsa3323/AdvancedArmorStands
          source-branch: master
          source-filepath: ./README.md
          destination-filepath: ./README.md
          github_token: ${{ secrets.PAT_TOKEN }}
